# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

matrix:
  fast_finish: true

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm@2.12.1
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g gulp
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: gulp test
