# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

matrix:
  fast_finish: true

# what combinations to test
environment:
  matrix:
    - nodejs_version: 8
      RESINTEST_EMAIL: 'test2+juan@resin.io'
      RESINTEST_USERNAME: 'test2_juan'
      RESINTEST_REGISTER_EMAIL: 'test2+register+juan@resin.io'
      RESINTEST_REGISTER_USERNAME: 'test2_register_juan'
    - nodejs_version: 6
      RESINTEST_EMAIL: 'test3+juan@resin.io'
      RESINTEST_USERNAME: 'test3_juan'
      RESINTEST_REGISTER_EMAIL: 'test3+register+juan@resin.io'
      RESINTEST_REGISTER_USERNAME: 'test3_register_juan'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@4
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test

notifications:

  - provider: Webhook
    url: https://webhooks.gitter.im/e/3d5ed28fa9ae4c25f46f
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
